module.exports = [
    {
        "name": "id",
        "addToResponse": true,
        "userWritable": false,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "age",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "sex",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "address",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "famsize",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "Pstatus",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "Medu",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "Fedu",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "Mjob",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "Fjob",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "traveltime",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "studytime",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "activities",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "higher",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "internet",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "romantic",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "freetime",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "goout",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "Dalc",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "Walc",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "absences",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    },
    {
        "name": "G3",
        "addToResponse": true,
        "userWritable": true,
        "canSortBy": false,
        "canFilterBy": true,
        "canSearchBy": true,
        "isJSON": false,
        "validateRule": "string",
        "sanitizeRule": "",
        "required": false
    }
]
