module.exports = {
    allFeatures: [
        "school",
        "sex",
        "age",
        "address",
        "famsize",
        "Pstatus",
        "Medu",
        "Fedu",
        "Mjob",
        "Fjob",
        "reason",
        "guardian",
        "traveltime",
        "studytime",
        "failures",
        "schoolsup",
        "famsup",
        "paid",
        "activities",
        "nursery",
        "higher",
        "internet",
        "romantic",
        "famrel",
        "freetime",
        "goout",
        "Dalc",
        "Walc",
        "health",
        "absences",
        "G1",
        "G2",
        "G3"
    ],
    
    trackedFeatures: [
        'age',
        'sex',
        'address',
        'famsize',
        'Pstatus',
        'Medu',
        'Fedu',
        'Mjob',
        'Fjob',
        'traveltime',
        'studytime',
        'activities',
        'higher',
        'internet',
        'romantic',
        'freetime',
        'goout',
        'Dalc',
        'Walc',
        'absences',
        'G3'
    ],
    
    url: 'https://ussouthcentral.services.azureml.net/workspaces/7ead72a1a47b41ef8af974222279c00d/services/8e4faeca10c64df7b545c67f77f16b21/execute?api-version=2.0&details=true'
}
